[FIX]inv.number for inv.name Description of the issue/feature this PR addresses: Throwing error when try to select 'Originating Sales Order Line'.
Current behavior before PR:
Raise following errors:
RecursionError: maximum recursion depth exceeded while calling a Python object
UnicodeError: unable to convert <odoo.tools.func.lazy object at 0x7f3af88aa240>

Desired behavior after PR is merged:
Select 'Originating Sales Order Line' normally.